### ISSUE TITLE
Crashes with react-router beta

### ISSUE THREAD

**Issue by kasperpeulen** [tylermcginnis/react-router-firebase-auth#14]
I get this error after upgrading to react-router beta:

```
Warning: Failed prop type: Invalid prop `children` supplied to `BrowserRouter`, expected a ReactNode.
    in BrowserRouter (at index.js:40)
    in App (at index.js:7)
```

**Comment by just214** [comment]
It appears that the issue is that `Match` and `Miss` have been removed from the React-Router API. I was able to resolve this issue by replacing these components with the `Router` and `Switch` components respectively. Please refer to the React-Router docs for more details. 

<https://reacttraining.com/react-router/>

I have created a fork with these changes and it appears to be working. You can find the fork here.

<https://github.com/gojutin/react-router-firebase-auth>

You will also need add your Firebase config object and  enable the Email/Password sign-in methods in the Firebase Console. 

@tylermcginnis I am happy to submit a pull request if you would like. I am still pretty green so the code may need some cross-checking. Also, if there is a better way to do this on GitHub, my apologies. I am still learning the ropes. By the way, thanks for the FullStack React book. It has helped me tremendously so far!

**Comment by Jasonjys** [comment]
@gojutin Hi, thanks for the fix! But I found another problem with Router.transitionTo() function in index.js file. How do you fix that? I am kinda new to React.

This is the error I am getting.
```
reactRouterDom.BrowserRouter.transitionTo is not a function
```

**Comment by just214** [comment]
@Jasonjys No problem. I had a hard time re-creating this error, but finally found it after I logged out. The problem seems to be another method `Router.transitionTo` that was removed from React-Router v4. I just removed this line from `src/components/index.js` and it seems to have fixed the problem. As far as I can tell, this line of code isn't needed. I may be overlooking something, but everything appears to be working just as intended. Hope this helps.

**Comment by Jasonjys** [comment]
@gojutin Thanks for the reply! I am wondering how am I gonna transit to other route since .transitionTo() does not work anymore. What function should I use to redirect to other routes?

**Comment by just214** [comment]
@Jasonjys The folks at React Router made some pretty big changes to the library. For rerouting, it appears that the preferred methods is to use the `Redirect` component that is supplied by React-Router. There is always the `Link` component as well. 

The React-Router team has also put together some great docs, including videos, for React-Router v4. The link is a little tricky to find but you can check it out here: 
[https://reacttraining.com/react-router/](https://reacttraining.com/react-router/)

Hope this helps and best of luck.

**Comment by verticalgrain** [comment]
@Jasonjys I had the same question and made a quick gist of how to redirect after a form submission, using the `Redirect` component:

https://gist.github.com/verticalgrain/195468e69f2ac88f3d9573d285b09764

**Comment by tylermcginnis** [comment]
Fixed. https://github.com/tylermcginnis/react-router-firebase-auth/commit/ddd308702d25645e7a7af6d20dfa4f771b9ca4ac
